Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -27,6 +27,16 @@ jobs:
     - name: Create local.properties
       run: echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> local.properties
 
+    - name: Verify Secret Injection
+      run: |
+        if grep -q "GOOGLE_API_KEY" local.properties; then
+          echo "Key successfully written to local.properties"
+        else
+          echo "Failed to write key"
+          exit 1
+        fi
+
+
     - name: Build with Gradle
       run: ./gradlew assembleDebug
 
